import React from 'react'

import "../Styles/blogs.css";

import {Link} from 'react-router-dom';


function Creativefour() {


    return (
        <div>
            <div className="three"><h1 className="page-header">Creative Reflection</h1></div>




            <div className="intro">
                <div className="h-entry" >








                    <p>
                    My creative project still revolves around geometric pattern but the project itself has changed quite a bit. My project now revolves around creating multiple different pieces of geometric art. My creative project changed because of my interests changing and what I wanted to investigate using my art. I wanted to create my patterns using js but instead I opted for CSS art which has always been an interest of mine. I wanted to see all the geometric patterns I could possibly make using CSS. To ensure the project utilises react there will be a few art pages and the user will be able to interact with the art pages. I am using the art aspect of the project to explore multiple different creative expressions using css, js and react. 
                    </p>

                    <p>
                    Patterns are a big part of my project thus I wanted to make them visible throughout my website. To achieve this, I added a subtle background of patterns. I do not want to detract from the websites text and cause distraction thus the image is a bit transparent and is not bright and does not move. I added patterns to the creative cards to further add a bit of my creative focus to the website. 

</p>

<p>My theory blogs do not have any patterns on the cards to ensure the focus is on the text and set a more serious tone than the fun patterns that the creative cards have. The theory blogs do however have icons. I will be replacing the icons I have now with icons that fit better with the theme and blog in question. </p>

                    <p>
                    <h3 className='page-header'>Internet Art proposal 2.0</h3>
                    </p>
                    <p>

                    My original idea for my website was to create Islamic geometric art using CSS and React. Creating net-art based on Islamic geometric art will highlight this artform giving the spotlight to Islamic art. I chose this as my creative project because it represents a religion and culture that is often demonised using the space to create positivity and appreciation instead.       </p>
                    <p>

                    While my original idea was to have the user input a country and a colour and the website would generate the pattern, I decided to go with a slightly different approach for my project. Instead, I will display a wide array of patterns generated by CSS. The patterns will sit next to each other depicting different geometric patterns. Instead of the user only seeing one pattern at a time the user can view a collection of patterns and browse the endless possibilities of geometric art patterns. To add interaction to the project the user will be able to change the colour of the patterns to see the patterns in different hues. This will allow the user to engage with the art and observe the patterns and how they may look in different colours. The idea behind having a large array of patterns means that the user does not have to be limited to one at a time and viewing the patterns in a gallery will allow the patterns to be compared. The vast variety of geometric art can thus be observed, and the endless combination of geometric elements can be acknowledged as well. I will constantly be adding more patterns to my gallery of patterns. I am to have at least forty different patterns by the end of the project. 
                      
                             </p>

                  

                    <p>
                            
                    Next, I wanted to add a Kaleidoscope of patterns to my project. Kaleidoscopes can show the geometric patterns in an interesting form. Watching how the colours and shapes flow is entertaining and to add more engagement between the user and the art, I will add a zoom and sizing ability to the project so the user can experiment with the kaleidoscope.   
                            
                             </p>



                </div>

            </div>

            <div className="more-btn display-flex align-center justify-center paddingxy-30">
                
                <Link to="/creativethree">
           <button className="more-btn pointer btn">Back</button>
                   </Link>
                   
                   <Link to="/creativefive">
           <button className="pagebtn pointer btn">Next</button>
                   </Link>
                </div>
        </div>




    );
}

export default Creativefour;
